execute_process(COMMAND "${PROBE}" "${MODE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 15)
if(result STREQUAL "0")
    message(FATAL_ERROR "Instrumentation did not stop the ${MODE} negative fixture")
endif()
if(MODE STREQUAL "address")
    set(expected "AddressSanitizer: heap-buffer-overflow")
else()
    set(expected "runtime error: signed integer overflow")
endif()
if(NOT "${output}${error}" MATCHES "${expected}")
    message(FATAL_ERROR "Missing ${MODE} diagnostic; result=${result}\n${output}\n${error}")
endif()
message(STATUS "${MODE} instrumentation detected its controlled negative fixture")
