# Disposable source copies only. Pass COMPILER, TEST_DIR and WORK outside sources.
if(NOT DEFINED COMPILER OR NOT DEFINED TEST_DIR OR NOT DEFINED WORK)
    message(FATAL_ERROR "Pass COMPILER, TEST_DIR and WORK")
endif()
get_filename_component(driver "${TEST_DIR}/.." ABSOLUTE)
set(killed 0)
set(controls 0)
foreach(mutation IN ITEMS control_protocol control_core control_os crc byte_order field_mask
                          first_failure activation ifcnt tick_rounding diagnostic_read diagnostic_write
                          reset_fault ack_rearm driver_fault activation_post_fault configure_post_fault)
    set(copy "${WORK}/${mutation}")
    file(MAKE_DIRECTORY "${copy}")
    file(COPY "${driver}/Inc" "${driver}/Src" DESTINATION "${copy}")
    set(test test_driver_full.c)
    set(sources "${copy}/Src/tmc2209.c" "${copy}/Src/tmc2209_ll.c" "${TEST_DIR}/fakes/fake_core.c")
    set(file "")
    set(needle "")
    set(replacement "")
    set(expected "")
    if(mutation STREQUAL "control_protocol" OR mutation STREQUAL "crc" OR mutation STREQUAL "byte_order")
        set(test test_crc_datagram.c)
    endif()
    if(mutation STREQUAL "crc")
        set(file "${copy}/Src/tmc2209_ll.c")
        set(needle "? 0x07u : 0u")
        set(replacement "? 0x09u : 0u")
        set(expected "memcmp(frame, requests[i], 4u) == 0")
    elseif(mutation STREQUAL "byte_order")
        set(file "${copy}/Src/tmc2209_ll.c")
        set(needle "out[3] = (uint8_t)(data >> 24u);")
        set(replacement "out[3] = (uint8_t)data;")
        set(expected "memcmp(frame, writes[i], 8u) == 0")
    elseif(mutation STREQUAL "field_mask")
        set(file "${copy}/Inc/tmc2209_reg.h")
        set(needle "UINT32_C(0x000F1F1F)")
        set(replacement "UINT32_C(0x000F1F3F)")
        set(expected "writers[i].fn(&unit, 1u << bit) == TMC2209_ERR_PARAM")
    elseif(mutation STREQUAL "first_failure")
        set(file "${copy}/Src/tmc2209_ll.c")
        set(needle "return first == TMC2209_OK ? cleanup : first;")
        set(replacement "(void)first; return cleanup;")
        set(expected "TMC2209_ReadReg(&unit, diagnostics[i].address, &data) == TMC2209_ERR_TIMEOUT")
    elseif(mutation STREQUAL "activation")
        set(file "${copy}/Src/tmc2209.c")
        set(needle "unit->address = addr;")
        set(replacement "unit->address = addr; unit->configured = true;")
        set(expected "TMC2209_Activate(&unit, 3) == TMC2209_ERR_STATE")
    elseif(mutation STREQUAL "ifcnt")
        set(file "${copy}/Src/tmc2209_ll.c")
        set(needle "(uint8_t)(after - before) != 1u")
        set(replacement "(uint8_t)(after - before) != 2u")
        set(expected "TMC2209_WriteRegVerified(&unit, 0, 0xC0) == TMC2209_OK")
    elseif(mutation STREQUAL "diagnostic_read")
        set(file "${copy}/Src/tmc2209.c")
        set(needle "{TMC2209_REG_OTP_READ, true, 0, 0, 0, 0}")
        set(replacement "{TMC2209_REG_OTP_READ, false, 0, 0, 0, 0}")
        set(expected "TMC2209_ReadReg(&unit, diagnostics[i].address, &data) == TMC2209_OK")
    elseif(mutation STREQUAL "diagnostic_write")
        set(file "${copy}/Src/tmc2209.c")
        set(needle "{TMC2209_REG_FACTORY_CONF, true, 0, 0, 0, 0}")
        set(replacement "{TMC2209_REG_FACTORY_CONF, true, 0x0000031Fu, 0, 0, 0}")
        set(expected "TMC2209_WriteReg(&unit, diagnostics[i].address, writes[j]) == TMC2209_ERR_PARAM")
    elseif(mutation STREQUAL "reset_fault")
        set(file "${copy}/Inc/tmc2209_reg.h")
        set(needle "TMC2209_GSTAT_FAULT_MASK      UINT32_C(0x00000007)")
        set(replacement "TMC2209_GSTAT_FAULT_MASK      UINT32_C(0x00000006)")
        set(expected "st == TMC2209_ERR_FAULT")
    elseif(mutation STREQUAL "ack_rearm")
        set(file "${copy}/Src/tmc2209_ll.c")
        set(needle "    unit->configured = false;")
        set(replacement "    if (reg != TMC2209_REG_GSTAT) unit->configured = false;")
        set(expected "st == TMC2209_OK && !unit.configured")
    elseif(mutation STREQUAL "driver_fault")
        set(file "${copy}/Src/tmc2209.c")
        set(needle "data & TMC2209_DRV_STATUS_FAULT_MASK")
        set(replacement "data & (TMC2209_DRV_STATUS_FAULT_MASK & ~UINT32_C(4))")
        set(expected "TMC2209_Configure(&unit, &cfg) == TMC2209_ERR_FAULT")
    elseif(mutation STREQUAL "activation_post_fault")
        set(file "${copy}/Src/tmc2209_ll.c")
        set(needle "if (first != TMC2209_OK) return first;\n    if (reg == TMC2209_REG_CHOPCONF && (data & 15u) != 0u)\n        return tmc2209_check_faults(unit);")
        set(replacement "if (first != TMC2209_OK) return first;\n    (void)unit; (void)reg; (void)data;")
        set(expected "attempt_activation(&unit, method) != TMC2209_OK")
    elseif(mutation STREQUAL "configure_post_fault")
        set(file "${copy}/Src/tmc2209.c")
        set(needle "st = tmc2209_check_faults(unit);\n    if (st == TMC2209_OK) unit->configured = true;\n    return st;")
        set(replacement "unit->configured = true;\n    return TMC2209_OK;")
        set(expected "boundary == 2u && phase == rx_count")
    endif()
    if(mutation STREQUAL "tick_rounding" OR mutation STREQUAL "control_os")
        set(test test_os_freertos.c)
        set(sources "${copy}/Src/tmc2209_os_freertos.c" "${TEST_DIR}/fakes/fake_rtos.c")
        if(mutation STREQUAL "tick_rounding")
            set(file "${copy}/Src/tmc2209_os_freertos.c")
            set(needle "+ 999u) / 1000u")
            set(replacement "+ 0u) / 1000u")
            set(expected "rtos_fake.last_wait == expected_ticks(1u)")
        endif()
    endif()
    if(NOT file STREQUAL "")
        file(READ "${file}" original)
        string(FIND "${original}" "${needle}" found)
        if(found EQUAL -1)
            message(FATAL_ERROR "${mutation}: mutation anchor no longer present")
        endif()
        string(REPLACE "${needle}" "${replacement}" modified "${original}")
        file(WRITE "${file}" "${modified}")
    endif()
    set(exe "${copy}/test.exe")
    execute_process(COMMAND "${COMPILER}" -std=c11 -O0 -Wall -Wextra -Wpedantic -Werror -Wundef
        -DTMC2209_NO_CONF=1 -DTMC2209_OS_NONE=0 -DTMC2209_OS_FREERTOS=1
        -DFAKE_TICK_BITS=16 -DFAKE_TICK_RATE=128
        "-I${copy}/Inc" "-I${TEST_DIR}" "-I${TEST_DIR}/fakes"
        "${TEST_DIR}/${test}" ${sources} -o "${exe}"
        RESULT_VARIABLE compiled OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
    file(WRITE "${copy}/compile.log" "${out}${err}")
    if(NOT compiled EQUAL 0)
        message(FATAL_ERROR "${mutation} failed to compile (not a killed mutation): ${err}")
    endif()
    execute_process(COMMAND "${exe}" RESULT_VARIABLE result
        OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 20)
    file(WRITE "${copy}/result.log" "${out}${err}")
    if(mutation MATCHES "^control_")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "${mutation}: unmodified control failed: ${out}${err}")
        endif()
        math(EXPR controls "${controls}+1")
        message(STATUS "${mutation}: unmodified control passed")
    else()
        string(FIND "${out}${err}" "${expected}" found)
        if(result EQUAL 0 OR found EQUAL -1)
            message(FATAL_ERROR "${mutation}: intended regression did not fail (${result}): ${out}${err}")
        endif()
        math(EXPR killed "${killed}+1")
        message(STATUS "${mutation}: intended assertion detected mutation")
    endif()
endforeach()
message(STATUS "Mutation sensitivity: ${controls} controls passed, ${killed} mutations detected")
