if(MODE STREQUAL "asan")
    set(argument 8)
    set(expected "AddressSanitizer: heap-buffer-overflow")
else()
    set(argument 2147483647)
    set(expected "runtime error: signed integer overflow")
endif()
execute_process(COMMAND "${EXE}" "${MODE}" "${argument}" RESULT_VARIABLE result
    OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 20)
file(WRITE "${LOG}" "${out}${err}")
if(result EQUAL 0 OR NOT "${out}${err}" MATCHES "${expected}")
    message(FATAL_ERROR "${MODE} did not detect the controlled invalid operation (${result}): ${out}${err}")
endif()
message(STATUS "${MODE} negative fixture detected with nonzero exit (${result})")
