execute_process(COMMAND "${WRITER}" RESULT_VARIABLE result OUTPUT_VARIABLE actual TIMEOUT 15)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Fixture writer failed: ${result}")
endif()
file(READ "${FIXTURE}" expected)
string(REPLACE "\r\n" "\n" actual "${actual}")
string(REPLACE "\r\n" "\n" expected "${expected}")
if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Committed v1 records differ from firmware serialization")
endif()
